openapi: 3.0.1
title: API del Mundo Disney
description: API Disney
termsOfService: http://example.com/terms/
contact:
  name: API Support
  url: http://www.example.com/support
  email: support@example.com
license:
  name: Apache 2.0
  url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:3000/api
    description: dev server
paths:
  /auth/register:
    post:
      summary: Crea un usuario.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/nuevousuario'
      responses: 
        '200':
          description: Registro exitoso.
        '500':
          description: Debe utilizar otra cuenta de email 
      tags:
        - nuevousuario
  /auth/login:
    post:
      summary: Inicio de sesión usuarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuarios'          
      responses:
        '200':
          description: Token
        '401':
          description: Error
      tags:
        - Usuarios
  /characters:
    get:
      security:
        - bearerAuth: []
      description: Visualizar todos los personajes
      summary: Listado de personajes.
      responses:
        '200':
          description: personajes
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
      tags:
        - Usuarios
    post:
      security:
        - bearerAuth: []
      description: Permite agregar personajes
      summary: agregar personajes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/agregaPersonajes'
      responses:
        '200':
          description: personajes
        '401':
          description: no se guardaron los cambios.
      tags:
        - Usuarios
  /characters/{id}:
    get:
      security:
        - bearerAuth: []
      description: permite visualizar cada personaje
      summary: muestra un personaje
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: personaje id
      responses:
        '200':
          description: personaje
        '401':
          description: el personaje no existe en la base de datos.
      tags:
        - Usuarios
    put:
      security:
        - bearerAuth: []
      description: Permite modificar los personajes
      summary: modificar los personajes
      parameters: 
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: personaje id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/editarPersonajes'
      responses:
        '200':
          description: personaje actualizado.
        '403':
          description: Debe iniciar sesión.
        '404':
          description: personaje no existe en la base de datos.  
      tags:
        - Usuarios
    delete:
      security:
        - bearerAuth: []
      description: Permite eliminar un personaje
      summary: elimina personaje
      parameters: 
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: personaje id
      responses:
        '200':
          description: personaje eliminado
        '403':
          description: Debe iniciar sesión.
        '404':
          description: personaje no existe en la base de datos. 
      tags:
        - Usuarios
  /movies:
    get:
      security:
        - bearerAuth: []
      description: Listado de todas las peliculas
      summary: Peliculas.
      responses:
        '200':
          description: peliculas
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
      tags:
        - Usuarios
    post:
      security:
        - bearerAuth: []
      description: Permite agregar peliculas
      summary: permite agregar peliculas
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/agregarPeliculas'
      responses:
        '200':
          description: peliculas
        '401':
          description: No se pudo guardar los cambios.
      tags:
        - Usuarios
  /movies/{id}:
    get:
      security:
        - bearerAuth: []
      description: Permite visualizar cada pelicula.
      summary: Pelicula
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: pelicula id
      responses:
        '200':
          description: pelicula
        '401':
          description: la pelicula no existe en la base de datos.
      tags:
        - Usuarios
    put:
      security:
        - bearerAuth: []
      description: Permite modificar las peliculas
      summary: modificar peliculas
      parameters: 
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: pelicula id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/editaPeliculas'
      responses:
        '200':
          description: pelicula actualizada.
        '403':
          description: Debe iniciar sesión.
        '404':
          description: La pelicula no existe en la base de datos.  
      tags:
        - Usuarios
    delete:
      security:
        - bearerAuth: []
      description: Permite eliminar peliculas
      summary: elimina peliculas
      parameters: 
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: pelicula id
      responses:
        '200':
          description: pelicula eliminada
        '403':
          description: Debe iniciar sesión.
        '404':
          description: La pelicula no existe en la base de datos. 
      tags:
        - Usuarios
components:
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    nuevousuario:
      properties:
        nombreUsuario: 
          type: string
        email: 
          type: email
        password: 
          type: string   
    Usuarios:
      properties:
        email:
          type: string
        password:
          type: string
    agregaPersonajes:
      properties:
        nombre:
          type: string
        imagen:
          type: integer
        edad:
          type: string
        peso:
          type: integer
        historia:
          type: string
    editarPersonajes:
      parameters: 
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: personaje id
      properties:
        nombre:
          type: string
        imagen:
          type: integer
        edad:
          type: string
        peso:
          type: integer
        historia:
          type: string
    agregarPeliculas:
      properties:
        titulo:
          type: string
        imagen:
          type: integer
        fecha:
          type: string
        calificacion:
          type: integer
    editaPeliculas:
      parameters: 
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: pelicula id
      properties:
        titulo:
          type: string
        imagen:
          type: integer
        fecha:
          type: string
        calificacion:
          type: integer